### ISSUE TITLE
BUG!!!

### ISSUE THREAD

**Issue by Gaaming** [xyfll7/CV-translation#1]
软件不好用，不能翻译，弹出错误框不能读取log.txt文件，卸载时还令我电脑蓝屏了。

**Comment by xyfll7** [comment]
log.txt 的 bug 已经修复了，
蓝屏问题，不要用我做的卸载图标卸载（我已经把那个卸载图标取消了）
用系统自带卸载功能卸载即可。

软件刚刚做好，你还是前几名用户呢，有bug 直接call我。在线改...

**Comment by Gaaming** [comment]
看 README.md 文件的更新日期应该是没有把修复版本的下载链接更新，等 UP 主更新后我再尝试一下。

**Comment by xyfll7** [comment]
要看 QTranser_Installer 文件夹的更新日期

**Comment by Gaaming** [comment]
试了下，还不错，谢谢 UP 主了:)

**Comment by Gaaming** [comment]
提个小意见，右上角 置顶和取消置顶 鼠标移上去文字不会高亮，不凑近看是看不见文字的。另外没找到软件的退出方式，虽然一直保留在托盘区也不碍事....

**Comment by xyfll7** [comment]
打开/退出方式：
![image](https://user-images.githubusercontent.com/28172140/56431472-5d69b480-62fc-11e9-8b20-421f14f18be5.png)

**Comment by Gaaming** [comment]
用任务栏设置退出 Qtranser 之后不能通过任务栏设置再次让 Qtranser 出现，双击桌面快捷图标也不能打开软件.......

**Comment by xyfll7** [comment]
![image](https://user-images.githubusercontent.com/28172140/56431771-97878600-62fd-11e9-997a-3401ea540f01.png)

**Comment by Gaaming** [comment]
emmm，还是不行

**Comment by xyfll7** [comment]
不能双击图标后不能重启是因为部分资源可能没有释放干净，需要重启任务栏本身。
本意是不想让用户看到 双击图标后会重启任务栏。

用这个文件重启一下任务栏：
C:\Program Files\QTranser\QTranser\toolsrestart.bat

**Comment by Gaaming** [comment]
可以了，那...我以后没事还是不关闭了...

**Comment by xyfll7** [comment]
下载这个文件：https://raw.githubusercontent.com/xyfll7/QTranser/master/QTranser/bin/Debug/tools/restart.bat
双击运行重启任务栏即可。
后续会彻底解决掉这个bug

**Comment by Gaaming** [comment]
好的，期待 UP 主解决这个 bug

**Comment by Gaaming** [comment]
在断网情况下复制文字会弹出对话框提示抛出异常，不太友好
![image](https://user-images.githubusercontent.com/30540592/56465477-72476480-6430-11e9-86bf-f29f681fafbd.png)

**Comment by xyfll7** [comment]
这个会和其它bug一并修改。
修复了重启电脑以后 详情页面会遮盖工具栏的错误。

**Comment by xyfll7** [comment]
修改好了你再试试。

**Comment by Gaaming** [comment]
emm，点击打开 QTranser 后一直黑屏。。

**Comment by Gaaming** [comment]
emm，等我下个 win10.iso 装个虚拟机再试试 QTranser，虽然是自己电脑，这么黑屏重启也不好。。。

**Comment by xyfll7** [comment]
现在怎么样？我这里倒是好好的。我试了好多遍才发出来的

**Comment by Gaaming** [comment]
安装的是新版本的，从桌面快捷方式打开点击确定后屏幕黑屏，从系统设置的应用里卸载旧版本还是会黑屏

**Comment by xyfll7** [comment]
那就是工具栏没能够正常重启。。

**Comment by Gaaming** [comment]
emmm，这确实是个问题。。

**Comment by xyfll7** [comment]
现在就这一个问题，很头疼啊。

**Comment by Gaaming** [comment]
那个重启工具栏的bat能用的话，可以直接代码调用那个bat吗？

**Comment by xyfll7** [comment]
可以的 restart.bat
我已经重新上传了安装包，我把重启任务栏延时增加到了3秒，你帮我试试^_^

**Comment by xyfll7** [comment]
我再另外一台电脑上试了也没问题

**Comment by Gaaming** [comment]
安装和断网部分没有问题，卸载部分还是会黑屏，卸载完成了也是黑屏
![image](https://user-images.githubusercontent.com/30540592/56503641-a44bea00-6548-11e9-84e3-2e97d455902b.png)

**Comment by xyfll7** [comment]
额，怎么会呢~~卸载又没有调用重启任务栏。

**Comment by Gaaming** [comment]
我重新试了试，双击快捷方式回出现两次 Windows 提示是否运行批处理，刚好这两个提示是覆盖住了程序本身的是否在工具栏创建的提示，只要点击了其中一个批处理的确定就会黑屏，卸载重新试了一下，提示需要关闭资源管理器，上次黑屏我是选了是，这次选否就不黑屏了
![image](https://user-images.githubusercontent.com/30540592/56504490-39e87900-654b-11e9-85e9-4b736d7c08dc.png)

**Comment by Gaaming** [comment]
那两次是否运行批处理都选择否，程序也能在工具栏上显示

**Comment by Gaaming** [comment]
emm，不运行批处理程序就会不能翻译，接着崩溃，然后工具栏重启......运行了批处理就会黑屏需要重启......

**Comment by Gaaming** [comment]
emmm，點了那個 Uni 結尾的批處理，emm，我又得重启了......

**Comment by xyfll7** [comment]
我知道原因了。你的安装过程需要请求管理员权限。而我的不需要。

**Comment by Gaaming** [comment]
emm，这个怎么解决呢。。

**Comment by xyfll7** [comment]
C:\Program Files\QTranser\QTranser\tools\installer.bat
任何时候都可以用这个批处理启动。

**Comment by xyfll7** [comment]
哈哈原来批处理文件也可以作为桌面快捷方式啊，那问题就解决了。

**Comment by Gaaming** [comment]
直接用 bat 文件打开，暂时没出其他问题 :)

**Comment by xyfll7** [comment]
版本更新，弃用了之前的翻译api，解决了一些已知bug，必须安装新版才能继续使用，抱歉。
