### ISSUE TITLE
是个好软件，就是bug太多

### ISSUE THREAD

**Issue by catcherxuefeng** [xyfll7/CV-translation#5]
1.任务栏字体发虚，改了个性化颜色后正常
2.安装过程太不友好，会触动一些别的软件，比如我的桌面管理器，资源管理器
3.查看历史记录会闪退

希望可以继续优化，多一些自定义配置，接口，本地字典，搜索功能开关

**Comment by xyfll7** [comment]
任务栏颜色、安装方式，这是两个相当棘手的问题。
